name: air_hokey_client
description: Client package for air hokey project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.9.1
  web_socket_channel: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  model:
    path: ../model

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
