name: air_hokey

repository: https://github.com/miyaji555/flutter_air_hokey

packages:
  - packages/*

sdkPath: .fvm/flutter_sdk

scripts:
  clean:
    run: melos exec -- "fvm flutter clean"

  pg:
    run: melos exec -- "fvm flutter pub get"

  clpg:
    run: melos exec -- "fvm flutter clean && fvm flutter pub get"

  build:
    run: melos exec -- "fvm dart run build_runner build --delete-conflicting-outputs"

  test:
    run: melos exec -- "fvm flutter test"

  analyze:
    run: melos exec -- "fvm flutter analyze ."

  format:
    run: melos exec -- "fvm dart format ."