name: Deploy to Google Cloud Run

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
          cache: true

      - name: pub activate dart_frog
        run: dart pub global activate dart_frog_cli

      - name: build
        run: |
          dart_frog build
        working-directory: packages/server

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/flutter_air_hokey:latest packages/server/build

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy flutter-air-hokey-server \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flutter_air_hokey:latest \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated